export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const GET_RESTAURANT = 'GET_RESTAURANT';
export const SET_RESTAURANT = 'SET_RESTAURANT';
